SELECT
    b.WRITER_ID,
    u.NICKNAME,
    CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS 전체주소,
    INSERT(INSERT(u.TLNO, 8, 0, '-'), 4, 0, '-') AS 전화번호
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY b.WRITER_ID DESC