SELECT 
    CAST(sub.YEAR AS UNSIGNED) AS YEAR,
    sub.m - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS d
INNER JOIN 
(
    SELECT 
        MAX(SIZE_OF_COLONY) AS m,
        DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR
    FROM ECOLI_DATA
    GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')
) AS sub
ON DATE_FORMAT(d.DIFFERENTIATION_DATE, '%Y') = sub.year
ORDER BY YEAR ASC, YEAR_DEV ASC;