SELECT DISTINCT(h.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
INNER JOIN CAR_RENTAL_COMPANY_CAR c
ON h.CAR_ID = c.CAR_ID
WHERE CAR_TYPE = '세단'
AND DATE_FORMAT(start_date, '%m') = '10'
ORDER BY h.CAR_ID DESC