SELECT i.ID, n.FISH_NAME, i.LENGTH FROM FISH_INFO i
INNER JOIN (SELECT MAX(LENGTH) as maxlen, FISH_TYPE FROM FISH_INFO
GROUP BY FISH_TYPE) sub
ON i.FISH_TYPE = sub.FISH_TYPE
INNER JOIN FISH_NAME_INFO n
ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.LENGTH = sub.maxlen